site_name: CSF302 - Algorithm Design and Analysis
site_url: https://norbutlepcha25.github.io/CSF302

use_directory_urls: false

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.tooltips
    - content.footnote.tooltips

  language: en
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      accent: blue
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Source Code Pro
  icon:
    logo: material/code-json

extra_css:
  - stylesheets/color.css
  - https://unpkg.com/katex@0/dist/katex.min.css

copyright: |
  &copy; 2025 <a href="https://github.com/norbutlepcha25" target="_blank" rel="noopener">Norbu Tshering Lepcha</a>

extra:
  generator: false
  base_url: /cSF302

markdown_extensions:
  - def_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

plugins:
  - search
  - glightbox
  - macros:
      module_name: main
      include_dir: macros
      include_yaml:
        - macros/vars.yml
        - macros/glossary.yml
        - macros/learning_outcomes.yml

  - minify:
      minify_html: true

nav:
  - Home: index.md

  - Unit 1:
      - Overview: unit1/overview.md
  #     - 1.1 Number Theory: unit1/topic1.md
  #     - 1.2 Combinatorics: unit1/topic2.md
  #     - 1.3 Combinatorics: unit1/topic3.md
  #     - 1.4 Basics of Game Theory: unit1/topic4.md
  #     - Summary: unit1/summary.md

  - Unit 2:
      - Overview: unit2/overview.md
      - 2.1 Asymptotic Analysis: unit2/topic1.md
      # - 2.2 Model of Computation (Word-RAM): unit2/topic2.md
  #     - 2.3 Role of Algorithms in Computing: unit2/topic3.md
  #     - 2.4 Analysing and Designing Algorithms: unit2/topic4.md
  #     - 2.5 O-notation, Ω-notation, and Θ-notation: unit2/topic5.md
  #     - 2.6 Standard Notation & Common Functions: unit2/topic6.md
  #     - Summary: unit2/summary.md

  - Unit 3:
      - Overview: unit3/overview.md
      - 3.1 Recurrences & Master Theorem (Analysis): unit3/topic1.md
      - 3.2 Iterative Method: unit3/topic2.md
      - 3.3 Recursion Trees: unit3/topic3.md
      - 3.4 Solving Recurrences (Substitution Method): unit3/topic4.md
      - 3.5 Solving Recurrences (Master Method): unit3/topic5.md
      - 3.6 Merge Sort Analysis: unit3/topic6.md
  #     - Summary: unit3/summary.md
  - Unit 4:
      - Overview: unit4/overview.md
      - 4.1 Divide & Conquer Algorithm Design: unit4/topic1.md
      - 4.2 Strassen's Algorithm for Matrix Multiplication: unit4/topic2.md
      - 4.3 Integer Multiplication: unit4/topic3.md
      - 4.4 Convolution & Fast Fourier Transform (FFT): unit4/topic4.md
      - 4.5 Binary Search and Ternary Search: unit4/topic5.md
      - 4.6 Efficient Modular Power (Exponentiation): unit4/topic6.md
      - 4.7 Efficient Matrix Modular Power (Exponentiation): unit4/topic7.md
  #     - Summary: unit4/summary.md

  - Unit 5:
      - Overview: unit5/overview.md
      - 5.1 Comparison-based Sorting Analysis: unit5/topic1.md
      - 5.2 Lower Bound for Sortings: unit5/topic2.md
      - 5.3 Quicksort Analysis and Performance: unit5/topic3.md
      - 5.4 Randomised Quicksort and Analysis: unit5/topic4.md
      - 5.5 Linear-Time Sorting( Counting Sort): unit5/topic5.md
      - 5.6 Linear-Time Sorting( Radix Sort): unit5/topic6.md
      - 5.7 Special Sorting Problems - Inversion Index: unit5/topic7.md
      - Summary: unit5/summary.md

  - Unit 6:
      - Overview: unit6/overview.md
      - 6.1 Dynamic Programming Design Principles: unit6/topic1.md
      - 6.2 Rod Cutting Problem: unit6/topic2.md
      - 6.3 Matrix Chain Multiplication: unit6/topic3.md
      - 6.4 Longest Common Subsequence: unit6/topic4.md
      - Summary: unit6/summary.md

  - Unit 7:
      - Overview: unit7/overview.md
      - 7.1 Greedy Algorithm Design Principles: unit7/topic1.md
      - 7.2 Fractional Knapsack Problem: unit7/topic2.md
      - 7.3 Huffman Coding: unit7/topic3.md
      - 7.4 Activity Selection Problems: unit7/topic4.md
      - 7.5 Dijkstra's Algorithm: unit7/topic5.md
      - 7.6 Minimum Spanning Tree (Prim's and Kruskal's Algorithms): unit7/topic6.md
      # - Summary: unit7/summary.md

  - Questions: questions.md
